openapi: "3.0.0"
info:
  version: 1.0.0
  title: Accounts Service
  license:
    name: MIT
servers:
- url: http://accounts.tp.io/v1
paths:
  /accounts:
    get:
      summary: Get list of accounts
      operationId: listAccounts
      tags:
      - accounts
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accounts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new account
      operationId: createAccounts
      tags:
      - accounts
      responses:
        '200':
          description: Object created succesfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /accounts/{accountId}:
    get:
      summary: Get Account Details
      operationId: showAccountById
      tags:
      - accounts
      parameters:
      - name: accountId
        in: path
        required: true
        description: The id of the account to retrieve
        schema:
          type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Account:
      required:
      - id
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        type:
          type: string
        owners:
          type: array
          items:
            type: string
        iban:
          type: string
        tag:
          type: string
        moneyAmount:
          type: string
    Accounts:
      type: array
      items:
        $ref: "#/components/schemas/Account"
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string